"""Tests for Markdown comment rendering."""

from __future__ import annotations

from gitowl.comment import COMMENT_MARKER, render_comment
from gitowl.diff_utils import DiffStats
from gitowl.models import Finding, FindingSource, ReviewResult, RiskLevel, Severity, UsageStats


def _stats() -> DiffStats:
    return DiffStats(files_changed=2, added_lines=10, removed_lines=4, changed_files=["a", "b"])


def test_render_includes_marker_and_risk() -> None:
    result = ReviewResult(summary="Summary here.", risk=RiskLevel.HIGH, findings=[])
    body = render_comment(result, _stats())
    assert COMMENT_MARKER in body
    assert "High" in body
    assert "Summary here." in body
    assert "+10/-4" in body


def test_render_no_findings_shows_clean() -> None:
    result = ReviewResult(summary="s", risk=RiskLevel.LOW, findings=[])
    assert "No issues flagged" in render_comment(result, _stats())


def test_footer_plain_when_no_usage() -> None:
    result = ReviewResult(summary="s", risk=RiskLevel.LOW, findings=[])
    body = render_comment(result, _stats())
    assert "Generated by [GitOwl]" in body
    # No usage => no token/cost/latency clutter.
    assert "tok" not in body


def test_footer_shows_usage_and_cost() -> None:
    result = ReviewResult(
        summary="s",
        risk=RiskLevel.LOW,
        findings=[],
        usage=UsageStats(
            model="openai/gpt-4o-mini",
            prompt_tokens=800,
            completion_tokens=200,
            total_tokens=1000,
            latency_ms=1800,
            estimated_cost_usd=0.0004,
        ),
    )
    body = render_comment(result, _stats())
    assert "openai/gpt-4o-mini" in body
    assert "1,000 tok" in body
    assert "~$0.0004" in body
    assert "1,800ms" in body


def test_footer_shows_cost_unknown() -> None:
    result = ReviewResult(
        summary="s",
        risk=RiskLevel.LOW,
        findings=[],
        usage=UsageStats(
            model="mystery/model",
            prompt_tokens=10,
            completion_tokens=5,
            total_tokens=15,
            latency_ms=500,
            estimated_cost_usd=None,
        ),
    )
    body = render_comment(result, _stats())
    assert "cost unknown" in body


def test_render_includes_suggestion_block() -> None:
    result = ReviewResult(
        summary="s",
        risk=RiskLevel.MEDIUM,
        findings=[
            Finding(
                source=FindingSource.AI,
                severity=Severity.ERROR,
                title="Weak hash",
                message="Use SHA-256.",
                file="auth.py",
                line=12,
                suggestion="hashlib.sha256(pw).hexdigest()",
            )
        ],
    )
    body = render_comment(result, _stats())
    assert "```suggestion" in body
    assert "hashlib.sha256(pw).hexdigest()" in body


def test_render_omits_suggestion_when_absent() -> None:
    result = ReviewResult(
        summary="s",
        risk=RiskLevel.LOW,
        findings=[
            Finding(
                source=FindingSource.AI,
                severity=Severity.INFO,
                title="Note",
                message="fyi",
                file="x.py",
                line=1,
            )
        ],
    )
    assert "```suggestion" not in render_comment(result, _stats())


def test_render_lists_findings_and_dismissed() -> None:
    result = ReviewResult(
        summary="s",
        risk=RiskLevel.MEDIUM,
        findings=[
            Finding(
                source=FindingSource.AI,
                severity=Severity.WARNING,
                title="Watch out",
                message="be careful",
                file="x.py",
                line=9,
            )
        ],
        dismissed=[
            Finding(
                source=FindingSource.SEMGREP,
                severity=Severity.INFO,
                title="fp",
                message="false positive",
                rule_id="rule.fp",
            )
        ],
    )
    body = render_comment(result, _stats())
    assert "Watch out" in body
    assert "x.py:9" in body
    assert "Dismissed as false positives" in body
    assert "rule.fp" in body
