"""Render a :class:`ReviewResult` as a structured Markdown PR comment."""

from __future__ import annotations

from devguard.diff_utils import DiffStats
from devguard.models import Finding, ReviewResult, RiskLevel, Severity

_RISK_BADGE = {
    RiskLevel.LOW: "🟢 **Low**",
    RiskLevel.MEDIUM: "🟡 **Medium**",
    RiskLevel.HIGH: "🔴 **High**",
}

_SEVERITY_ICON = {
    Severity.ERROR: "🔴",
    Severity.WARNING: "🟡",
    Severity.INFO: "🔵",
}

# Marker so DevGuard can find and update its own previous comment on a PR.
COMMENT_MARKER = "<!-- devguard-review -->"


def _finding_line(f: Finding) -> str:
    icon = _SEVERITY_ICON.get(f.severity, "•")
    loc = f.location()
    src = f.rule_id or f.source.value
    return f"- {icon} **{f.title}** (`{loc}`, _{src}_)\n  {f.message}"


def render_comment(result: ReviewResult, stats: DiffStats) -> str:
    """Build the full Markdown comment body."""
    lines: list[str] = [
        COMMENT_MARKER,
        "## 🛡️ DevGuard Review",
        "",
        f"**Risk:** {_RISK_BADGE.get(result.risk, result.risk.value)}  ·  "
        f"**Files changed:** {stats.files_changed}  ·  "
        f"**Lines:** +{stats.added_lines}/-{stats.removed_lines}",
        "",
        result.summary,
        "",
    ]

    if result.findings:
        lines.append(f"### Findings ({len(result.findings)})")
        lines.extend(_finding_line(f) for f in result.findings)
        lines.append("")
    else:
        lines.append("### Findings")
        lines.append("_No issues flagged. ✅_")
        lines.append("")

    if result.dismissed:
        lines.append(
            f"<details><summary>Dismissed as false positives "
            f"({len(result.dismissed)})</summary>\n"
        )
        lines.extend(f"- `{f.rule_id or f.title}` at {f.location()}" for f in result.dismissed)
        lines.append("\n</details>")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [DevGuard](https://github.com/MarutiDubey/DevGuard)._")
    return "\n".join(lines)
