"""Generate a pull-request description from a diff.

Parallel to :mod:`devguard.reviewer`, but instead of scoring risk it produces a
human-readable PR body: an AI summary + a bullet list of changes. The CLI can
print it or (for a real PR) write it into the PR body between markers, leaving
any hand-written text intact.
"""

from __future__ import annotations

from devguard.ai_client import get_provider
from devguard.config import Config
from devguard.logging_config import get_logger
from devguard.models import PrDescription

logger = get_logger(__name__)

# Markers delimiting DevGuard's section inside a PR body, so a re-run replaces
# only its own block and never clobbers text the author wrote.
DESCRIBE_BEGIN = "<!-- devguard-describe:begin -->"
DESCRIBE_END = "<!-- devguard-describe:end -->"


def describe_diff(diff: str, config: Config) -> PrDescription:
    """Ask the configured provider for a PR description of ``diff``."""
    logger.info("Generating PR description")
    provider = get_provider(config.ai)
    return provider.describe(diff)


def render_description(desc: PrDescription) -> str:
    """Render a :class:`PrDescription` as a Markdown PR body."""
    lines = [f"## {desc.title}", "", desc.summary, ""]
    if desc.changes:
        lines.append("### Changes")
        lines.extend(f"- {c}" for c in desc.changes)
        lines.append("")
    lines.append("---")
    lines.append("_Description generated by [DevGuard](https://github.com/MarutiDubey/DevGuard)._")
    return "\n".join(lines)


def merge_into_body(existing_body: str | None, section: str) -> str:
    """Insert or replace DevGuard's marked section within ``existing_body``.

    A first run appends the section (wrapped in markers) below any existing
    text; a re-run replaces the previously-inserted block in place.
    """
    block = f"{DESCRIBE_BEGIN}\n{section}\n{DESCRIBE_END}"
    body = existing_body or ""

    begin = body.find(DESCRIBE_BEGIN)
    end = body.find(DESCRIBE_END)
    if begin != -1 and end != -1 and end > begin:
        before = body[:begin].rstrip()
        after = body[end + len(DESCRIBE_END) :].lstrip()
        parts = [p for p in (before, block, after) if p]
        return "\n\n".join(parts)

    return f"{body.rstrip()}\n\n{block}".lstrip() if body.strip() else block
