"""Render a :class:`ReviewResult` as a structured Markdown PR comment."""

from __future__ import annotations

from gitowl.diff_utils import DiffStats
from gitowl.models import Finding, ReviewResult, RiskLevel, Severity

_RISK_BADGE = {
    RiskLevel.LOW: "🟢 **Low Risk**",
    RiskLevel.MEDIUM: "⚠️ **Medium Risk**",
    RiskLevel.HIGH: "🚨 **High Risk**",
}

_SEVERITY_ICON = {
    Severity.ERROR: "🔴",
    Severity.WARNING: "🟡",
    Severity.INFO: "🔵",
}

# Marker so GitOwl can find and update its own previous comment on a PR.
COMMENT_MARKER = "<!-- gitowl-review -->"

# Branded header shown at the top of every PR comment (mirrors CodeRabbit style).
_HEADER = "\n".join(
    [
        '<div align="center">',
        "",
        '<a href="https://github.com/MarutiDubey/GitOwl">',
        '<img src="https://raw.githubusercontent.com/MarutiDubey/GitOwl/main/docs/logo.svg"',
        '     height="52" alt="GitOwl" />',
        "</a>",
        "",
        "## GitOwl Review",
        "",
        "</div>",
        "",
        "---",
    ]
)


def _finding_line(f: Finding) -> str:
    icon = _SEVERITY_ICON.get(f.severity, "•")
    loc = f.location()
    
    lines = [
        f"> {icon} **{f.title}**  `{loc}`",
        "> ",
    ]
    for msg_line in f.message.splitlines():
        lines.append(f"> {msg_line}" if msg_line else ">")
        
    if f.suggestion:
        lines.append("> ")
        lines.append("> ```suggestion")
        for sl in f.suggestion.splitlines():
            lines.append(f"> {sl}" if sl else ">")
        lines.append("> ```")
    
    return "\n".join(lines) + "\n"


def render_error_comment(error_msg: str) -> str:
    """Build a branded error comment so API failures are visible on the PR."""
    return "\n".join(
        [
            COMMENT_MARKER,
            _HEADER,
            "",
            "---",
            "",
            "⚠️ **GitOwl could not complete the review.**",
            "",
            f"**Error:** `{error_msg}`",
            "",
            "**Common fixes:**",
            "- Check that `AI_API_KEY` is set in *Settings → Secrets and variables → Actions*.",
            "- Verify your API key is valid and has sufficient credits.",
            "- Check the [Actions log](../../actions) for the full error trace.",
            "",
            "---",
            "_[GitOwl](https://github.com/MarutiDubey/GitOwl) · open an issue if this persists_",
        ]
    )


def render_comment(result: ReviewResult, stats: DiffStats) -> str:
    """Build the full Markdown comment body."""
    lines: list[str] = [
        COMMENT_MARKER,
        _HEADER,
        f"> {_RISK_BADGE.get(result.risk, result.risk.value)}  ·  "
        f"**{stats.files_changed} file" + ("s" if stats.files_changed != 1 else "") + "**  ·  "
        f"+{stats.added_lines}/-{stats.removed_lines}",
        ">",
    ]
    for sl in result.summary.splitlines():
        lines.append(f"> {sl}" if sl else ">")
    lines.append("")

    if result.findings:
        lines.append(f"### FINDINGS ({len(result.findings)})\n")
        lines.extend(_finding_line(f) for f in result.findings)
    else:
        lines.append("### FINDINGS\n")
        lines.append("_No issues flagged. ✅_\n")

    if result.dismissed:
        lines.append(
            f"<details><summary>Dismissed as false positives "
            f"({len(result.dismissed)})</summary>\n"
        )
        lines.extend(f"- `{f.rule_id or f.title}` at {f.location()}" for f in result.dismissed)
        lines.append("\n</details>")
        lines.append("")

    lines.append("---")
    lines.append(_footer(result))
    return "\n".join(lines)


def _footer(result: ReviewResult) -> str:
    """The attribution line, extended with usage stats when available."""
    base = "_Generated by [GitOwl](https://github.com/MarutiDubey/GitOwl)."
    usage = result.usage
    if usage is None:
        return base + "_"
    cost = (
        f"~${usage.estimated_cost_usd:.4f}"
        if usage.estimated_cost_usd is not None
        else "cost unknown"
    )
    return (
        f"{base} · {usage.model} · {usage.total_tokens:,} tok · "
        f"{cost} · {usage.latency_ms:,}ms_"
    )
