"""Render a :class:`ReviewResult` as a structured Markdown PR comment."""

from __future__ import annotations

from gitowl.diff_utils import DiffStats
from gitowl.models import Finding, ReviewResult, RiskLevel, Severity

_RISK_BADGE = {
    RiskLevel.LOW: "🟢 **Low**",
    RiskLevel.MEDIUM: "🟡 **Medium**",
    RiskLevel.HIGH: "🔴 **High**",
}

_SEVERITY_ICON = {
    Severity.ERROR: "🔴",
    Severity.WARNING: "🟡",
    Severity.INFO: "🔵",
}

# Marker so GitOwl can find and update its own previous comment on a PR.
COMMENT_MARKER = "<!-- gitowl-review -->"


def _finding_line(f: Finding) -> str:
    icon = _SEVERITY_ICON.get(f.severity, "•")
    loc = f.location()
    src = f.rule_id or f.source.value
    line = f"- {icon} **{f.title}** (`{loc}`, _{src}_)\n  {f.message}"
    if f.suggestion:
        # Flush-left, verbatim code so the block stays copy-pasteable now and
        # commit-ready when we post these as inline review comments later.
        line += f"\n\n```suggestion\n{f.suggestion}\n```"
    return line


def render_comment(result: ReviewResult, stats: DiffStats) -> str:
    """Build the full Markdown comment body."""
    lines: list[str] = [
        COMMENT_MARKER,
        "## 🛡️ GitOwl Review",
        "",
        f"**Risk:** {_RISK_BADGE.get(result.risk, result.risk.value)}  ·  "
        f"**Files changed:** {stats.files_changed}  ·  "
        f"**Lines:** +{stats.added_lines}/-{stats.removed_lines}",
        "",
        result.summary,
        "",
    ]

    if result.findings:
        lines.append(f"### Findings ({len(result.findings)})")
        lines.extend(_finding_line(f) for f in result.findings)
        lines.append("")
    else:
        lines.append("### Findings")
        lines.append("_No issues flagged. ✅_")
        lines.append("")

    if result.dismissed:
        lines.append(
            f"<details><summary>Dismissed as false positives "
            f"({len(result.dismissed)})</summary>\n"
        )
        lines.extend(f"- `{f.rule_id or f.title}` at {f.location()}" for f in result.dismissed)
        lines.append("\n</details>")
        lines.append("")

    lines.append("---")
    lines.append(_footer(result))
    return "\n".join(lines)


def _footer(result: ReviewResult) -> str:
    """The attribution line, extended with usage stats when available."""
    base = "_Generated by [GitOwl](https://github.com/MarutiDubey/GitOwl)."
    usage = result.usage
    if usage is None:
        return base + "_"
    cost = (
        f"~${usage.estimated_cost_usd:.4f}"
        if usage.estimated_cost_usd is not None
        else "cost unknown"
    )
    return (
        f"{base} · {usage.model} · {usage.total_tokens:,} tok · "
        f"{cost} · {usage.latency_ms:,}ms_"
    )
